name: Run Tests

on:
  workflow_call:

jobs:
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker build
        run: make docker-build
  test:
    name: Run tests
    env:
      GOPATH: /tmp/go
    runs-on: ubuntu-latest
    steps:
      - name: Create GOPATH
        run: mkdir -p /tmp/go
      - uses: actions/setup-go@v3
        with:
          go-version: ">=1.18.0"
          check-latest: true
      - uses: actions/checkout@v2
      - name: Test
        run: make test
